### ISSUE TITLE
kodi-inputstream-adaptive

### ISSUE THREAD

**Issue by Teknoist** [zjoasan/netflix-install-script#4]
After try kodi want to install kodi-inputstream-adaptive

**Comment by zjoasan** [comment]
Sorry haven't got around to fiddle with this for a while, was that on an OSMC install?

**Comment by Teknoist** [comment]
yeap rp3-osmc

**Comment by zjoasan** [comment]
Strange since on OSMC you got inputstream-adaptive installed by default, there is no kodi-inputstream-adaptive.deb in OSMC+Debian(stretch as we speak at least) repositorys.
