### ISSUE TITLE
Wrong netflix-repo.zip add-on repository downloaded on osmc/kodi 18.9

### ISSUE THREAD

**Issue by davoper** [zjoasan/netflix-install-script#8]
Ran the netflix_prep_install.sh script on Raspberry Pi 2b / osmc with kodi version 18.9 and it seamed like it was assuming kodi version was 19.x instead of 18.x
Once the script completed, it downloaded
https://github.com/castagnait/repository.castagnait/raw/matrix/repository.castagnait-1.0.0.zip
from matrix branch instead of
https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.1.zip
from current master branch of https://github.com/castagnait/repository.castagnait repository.

Maybe I did something wrong, but though to report it just in case.

I corrected this manually by removing wrong repository, restarting kodi and then loading add-in from correct .zip file.

**Comment by davoper** [comment]
I think this is the problem in the script:
Line:
Version=19
should be:
version=19

(case sensitive $version is not equal to Version)

**Comment by zjoasan** [comment]
Sorry it took so long to get to this, still adjusting to the 6 months old girl here at home.

Fixed along with a couple other small changes

https://github.com/zjoasan/netflix-install-script/commit/1c622c35d49cbd74eaeccc545264f0132db5a600
